### ISSUE TITLE
Description- unifinedunifinedunifined

### ISSUE THREAD

**Issue by Tom-ahawk** [kodi1/meteoalarm#5]
The N00b I am, cant get it to work using your code example. Any ideas why?

```
      type: custom:flex-table-card
      title: today
      entities:
        include: sensor.w_alert
      columns:
        - attr_as_list: today
          modify: x.code.concat(' ', x.event)
          name: event
        - attr_as_list: today
          modify: x.txt
          name: description
        - attr_as_list: today
          modify: x.end
          name: expire
```

My sensor data:
![image](https://user-images.githubusercontent.com/35527507/74108091-c9acf180-4b76-11ea-8c02-b3da34b2099e.png)

![image](https://user-images.githubusercontent.com/35527507/74108096-d5001d00-4b76-11ea-9963-a2e35f441e79.png)

![image](https://user-images.githubusercontent.com/35527507/74108098-ddf0ee80-4b76-11ea-9be5-2e0669a7733e.png)
