### ISSUE TITLE
Event description is not properly fetched.

### ISSUE THREAD

**Issue by daha76** [kodi1/meteoalarm#9]
Hello,

I'd like the idea to get a meteo alarm data for my home, but I found the issue with fetching event description. Used regular expression ('^(?P<lang>.*?):\s*(?P<desc>.*)') isn't working well and response data of my city (Kosice, Slovakia) it looks like this:

```html
<div class="text">
  slovenčina: 
  <br>
   V okrese Košice
  <br>
  sa vo výške 5 cm nad povrchom OJEDINELE očakáva dosiahnutie minimálnej teploty vzduchu -3 - 0 °C.
  <br>
Takýto prízemný mráz predstavuje potenciálne nebezpečenstvo pre teplomilné rastliny.
  <br>
  <br> 
  <cap:instruction> 
    ZVÝŠTE POZORNOSŤ, sledujte najčerstvejšie predpovede počasia.
    <br>
    Očakávajte menšie obmedzenia aktivít vonku.
  </cap:instruction> 
  <p>
    english: 
    <br>
     No detailed description for this language. See warning details in Slovak version.
    <br>
    <br> 
    <cap:instruction> 
      BE AWARE, keep up to date with the latest weather forecast.
      <br>
      Expect some minor disruption to outdoor activities.
    </cap:instruction>
    &nbsp;
  </p>
</div>
```

Result will look like this:

**Match 1:**
```
lang | slovenčina
desc | <br> V okrese Košice<br>
```
**Match 2:**
```
lang | Takýto prízemný mráz predstavuje potenciálne nebezpečenstvo pre teplomilné rastliny.<br><br> <cap
desc | instruction>
```
**Match 3:**
```
lang | Očakávajte menšie obmedzenia aktivít vonku.</cap
desc | instruction> <p>
```
**Match 4:**
```
lang | english
desc | <br> No detailed description for this language. See warning details in Slovak version.<br><br> <cap:instruction>
```
**Match 5:**
```
lang | Expect some minor disruption to outdoor activities.</cap
desc | instruction>&nbsp;</p>
```
and the result is quite incomplete and sensor returns incomplete data like this:
```yaml
attribution: Data provided by meteoalarm.eu
location: košice
today: []
tomorrow:
  - event: Extreme low temperature
    code: Yellow
    start: '17.04.2020 01:00 CEST'
    end: '17.04.2020 07:00 CEST'
    slovenčina: V okrese Košice
    english: >-
      No detailed description for this language. See warning details in Slovak
      version.  
unit_of_measurement: events
friendly_name: weather_alert
icon: 'mdi:weather-lightning-rainy'
```
 
Would it be possible to improve description parsing?
